<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="4a1178d159df" failures="1" tests="5" name="passengers-count-4" time="19.876" errors="0" timestamp="2023-12-30T13:45:45 GMT">
  <testcase classname="com.automation.selenium_docker.flightreservation.FlightReservationTest" name="userRegistrationTest" time="7.014"/>
  <testcase classname="com.automation.selenium_docker.flightreservation.FlightReservationTest" name="registrationConfirmationTest" time="1.008"/>
  <testcase classname="com.automation.selenium_docker.flightreservation.FlightReservationTest" name="flightSearchTest" time="3.576"/>
  <testcase classname="com.automation.selenium_docker.flightreservation.FlightReservationTest" name="flightSelectionTest" time="1.523"/>
  <testcase classname="com.automation.selenium_docker.flightreservation.FlightReservationTest" name="flightReservationConfirmationTest" time="1.488">
    <failure type="java.lang.AssertionError" message="expected [$238 USD] but found [$2338 USD]">
      <![CDATA[java.lang.AssertionError: expected [$238 USD] but found [$2338 USD]
at com.automation.selenium_docker.flightreservation.FlightReservationTest.flightReservationConfirmationTest(FlightReservationTest.java:76)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 23 stack frames]]>
    </failure>
  </testcase> <!-- flightReservationConfirmationTest -->
</testsuite> <!-- passengers-count-4 -->
